version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: dead_god_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - postgres-data:/var/lib/postgresql/data
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: blablablablad777@gmail.com
            PGADMIN_DEFAULT_PASSWORD: rikori1702
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        restart: always

    dead-god:
        stdin_open: true
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - ./prisma:/dead-god/prisma
            - ./src:/dead-god/src
            - dg-node-modules:/dead-god/node_modules
            - dg-next:/dead-god/.next

volumes:
    postgres-data:
    pgadmin-data:
    dg-node-modules:
    dg-next:
